exclude_paths:
- jobs/awslogs-bionic/templates/helpers/
- jobs/awslogs-bionic/templates/bin/monit_debugger
- jobs/awslogs-bionic/templates/bin/ctl
- jobs/awslogs-bionic/templates/bin/scanner-ctl
plugins:
  shellcheck:
    enabled: true
